apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:15-alpine
        command: ['sh', '-c', 
          'until pg_isready -h postgres-db -U postgres -d VEHICLE_AUTH_DB; do echo waiting for database; sleep 2; done;']
        env:
        - name: PGPASSWORD
          value: "super_secret_password"
      containers:
        - name: auth-service
          image: brightdotdev/vta-auth-service:v1
          ports:
            - containerPort: 8103
          envFrom:
            - configMapRef:
                name: global-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8103
      targetPort: 8103