apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch-service
  template:
    metadata:
      labels:
        app: dispatch-service
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:15-alpine
        command: ['sh', '-c', 
          'until pg_isready -h postgres-db -U postgres -d VEHICLE_DISPATCH_DB; do echo waiting for database; sleep 2; done;']
        env:
        - name: PGPASSWORD
          value: "super_secret_password"
      containers:
        - name: dispatch-service
          image: brightdotdev/vta-dispatch-service:v1
          ports:
            - containerPort: 8105
          envFrom:
            - configMapRef:
                name: global-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"