apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: brightdotdev/vta-logging-service:v1
          ports:
            - containerPort: 8104
          envFrom:
            - configMapRef:
                name: global-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging-service
  ports:
    - port: 8104
      targetPort: 8104