apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-config
data:
  ############################################
  # SERVICE PORTS
  ############################################
  API_GATEWAY_PORT: "8102"
  AUTH_SERVICE_APP_PORT: "8103"
  DISPATCH_SERVICE_APP_PORT: "8105"
  LOGGING_SERVICE_APP_PORT: "8104"
  VEHICLE_SERVICE_APP_PORT: "8106"

  ############################################
  # DATABASE CONFIGURATION (NON-SENSITIVE)
  ############################################
  POSTGRES_DB_DEFAULT: "postgres"
  POSTGRES_DB_AUTH: "VEHICLE_AUTH_DB"
  POSTGRES_DB_DISPATCH: "VEHICLE_DISPATCH_DB"
  POSTGRES_DB_VEHICLE: "VEHICLE_VEHICLE_DB"
  AUTH_SERVICE_SQL_URL: "jdbc:postgresql://postgres-db:5432/VEHICLE_AUTH_DB"
  DISPATCH_SERVICE_SQL_URL: "jdbc:postgresql://postgres-db:5432/VEHICLE_DISPATCH_DB"
  VEHICLE_SERVICE_SQL_URL: "jdbc:postgresql://postgres-db:5432/VEHICLE_VEHICLE_DB"
  LOGGING_SERVICE_MONGO_URL: "mongodb://mongo-logging:27017/loggingdb"

  ############################################
  # SERVICE COMMUNICATION
  ############################################
  MESSAGE_TYPE: "webClient"
  API_GATEWAY_URL: "http://api-gateway:8102"
  LOGGING_SERVICE_URL: "http://logging-service:8104"
  DISPATCH_SERVICE_URL: "http://dispatch-service:8105"
  AUTH_SERVICE_URL: "http://auth-service:8103"
  VEHICLE_SERVICE_URL: "http://vehicle-service:8106"

  ############################################
  # ADMIN TOOLS
  ############################################
  AUTO_PORT_URL: "http://user-auto-port-web:3001"
  ADMIN_DESK_URL: "http://admin-desk-web:3000"
