apiVersion: v1
kind: Secret
metadata:
  name: vehicle-secrets
type: Opaque
stringData:
  ############################################
  # DATABASE CONFIGURATION (SENSITIVE)
  ############################################
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "super_secret_password"

  ############################################
  # SECURITY CONFIGURATION
  ############################################
  API_INTERNAL_KEY: "internalKey"
  JWT_SECRET: "431da76bdce7104b0a69902ede07459b0087f110d969fb15fef07afc899012ac07bc3435d063f8619c1523d917e84024ee8784c3f2e619c1efb770d86221bf35"
  JWT_EXP: "604800000"

  ############################################
  # RABBITMQ CONFIGURATION
  ############################################
  RABBITMQ_URL: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "app_rabbit"
  RABBITMQ_PASSWORD: "super_secret_rabbit"

  ############################################
  # ADMIN TOOLS (SENSITIVE)
  ############################################
  PGADMIN_DEFAULT_EMAIL: "admin@example.com"
  PGADMIN_DEFAULT_PASSWORD: "admin"
